"""adicionar tabelas de pedidos e mesas

Revision ID: 281db827dfba
Revises: 4d12f432fd4b
Create Date: 2026-03-26 18:35:37.790560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '281db827dfba'
down_revision: Union[str, None] = '4d12f432fd4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=True),
    sa.Column('qrcode_url', sa.String(length=255), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('mesa_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('endereco_entrega', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('taxa_entrega', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('metodo_pagamento', sa.String(length=20), nullable=True),
    sa.Column('status_pagamento', sa.String(length=20), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('agendado_para', sa.DateTime(), nullable=True),
    sa.Column('pontos_gerados', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['mesa_id'], ['mesas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_cliente_id'), 'pedidos', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_pedidos_numero'), 'pedidos', ['numero'], unique=True)
    op.create_table('variantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variantes_produto_id'), 'variantes', ['produto_id'], unique=False)
    op.create_table('pedido_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('variante_id', sa.Integer(), nullable=True),
    sa.Column('nome_snapshot', sa.String(length=200), nullable=False),
    sa.Column('preco_snapshot', sa.Float(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['variante_id'], ['variantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_itens_pedido_id'), 'pedido_itens', ['pedido_id'], unique=False)
    op.create_table('pedido_item_modificadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pedido_item_id', sa.Integer(), nullable=False),
    sa.Column('modificador_id', sa.Integer(), nullable=False),
    sa.Column('nome_snapshot', sa.String(length=100), nullable=False),
    sa.Column('preco_snapshot', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['modificador_id'], ['modificadores.id'], ),
    sa.ForeignKeyConstraint(['pedido_item_id'], ['pedido_itens.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_item_modificadores_pedido_item_id'), 'pedido_item_modificadores', ['pedido_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_item_modificadores_pedido_item_id'), table_name='pedido_item_modificadores')
    op.drop_table('pedido_item_modificadores')
    op.drop_index(op.f('ix_pedido_itens_pedido_id'), table_name='pedido_itens')
    op.drop_table('pedido_itens')
    op.drop_index(op.f('ix_variantes_produto_id'), table_name='variantes')
    op.drop_table('variantes')
    op.drop_index(op.f('ix_pedidos_numero'), table_name='pedidos')
    op.drop_index(op.f('ix_pedidos_cliente_id'), table_name='pedidos')
    op.drop_table('pedidos')
    op.drop_table('mesas')
    # ### end Alembic commands ###
