"""criar tabelas iniciais

Revision ID: 4d12f432fd4b
Revises: 
Create Date: 2026-03-24 20:45:30.897867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d12f432fd4b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=False),
    sa.Column('endereco_padrao', sa.Text(), nullable=True),
    sa.Column('pontos', sa.Integer(), nullable=False),
    sa.Column('nivel_fidelidade', sa.String(length=20), nullable=False),
    sa.Column('total_pedidos', sa.Integer(), nullable=False),
    sa.Column('total_gasto', sa.Float(), nullable=False),
    sa.Column('segmento', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('ultimo_pedido', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clientes_telefone'), 'clientes', ['telefone'], unique=True)
    op.create_table('configuracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_loja', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('banner_url', sa.String(length=255), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=False),
    sa.Column('chave_pix', sa.String(length=100), nullable=True),
    sa.Column('tipo_chave_pix', sa.String(length=20), nullable=True),
    sa.Column('taxa_entrega', sa.Float(), nullable=False),
    sa.Column('pedido_minimo', sa.Float(), nullable=False),
    sa.Column('tempo_entrega_min', sa.Integer(), nullable=False),
    sa.Column('tempo_entrega_max', sa.Integer(), nullable=False),
    sa.Column('aceitar_pedidos', sa.Boolean(), nullable=False),
    sa.Column('mensagem_fechado', sa.Text(), nullable=False),
    sa.Column('instagram_url', sa.String(length=255), nullable=True),
    sa.Column('horarios_json', sa.Text(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('foto_url', sa.String(length=255), nullable=True),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.Column('destaque', sa.Boolean(), nullable=False),
    sa.Column('controle_estoque', sa.Boolean(), nullable=False),
    sa.Column('estoque_atual', sa.Integer(), nullable=False),
    sa.Column('estoque_minimo', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_produtos_categoria_id'), 'produtos', ['categoria_id'], unique=False)
    op.create_table('grupos_modificadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('obrigatorio', sa.Boolean(), nullable=False),
    sa.Column('selecao_minima', sa.Integer(), nullable=False),
    sa.Column('selecao_maxima', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grupos_modificadores_produto_id'), 'grupos_modificadores', ['produto_id'], unique=False)
    op.create_table('modificadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('preco_adicional', sa.Float(), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos_modificadores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modificadores_grupo_id'), 'modificadores', ['grupo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_modificadores_grupo_id'), table_name='modificadores')
    op.drop_table('modificadores')
    op.drop_index(op.f('ix_grupos_modificadores_produto_id'), table_name='grupos_modificadores')
    op.drop_table('grupos_modificadores')
    op.drop_index(op.f('ix_produtos_categoria_id'), table_name='produtos')
    op.drop_table('produtos')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('configuracoes')
    op.drop_index(op.f('ix_clientes_telefone'), table_name='clientes')
    op.drop_table('clientes')
    op.drop_table('categorias')
    # ### end Alembic commands ###
